# Generated by Django 5.0.6 on 2024-05-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='incentives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seal', models.TextField()),
                ('incentives', models.TextField()),
                ('order_number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='job_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_reception', models.TextField()),
                ('date_dismissal', models.TextField()),
                ('sail', models.TextField()),
                ('position', models.TextField()),
                ('ordet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('series', models.TextField()),
                ('number', models.TextField()),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField()),
                ('year_birth', models.TextField()),
                ('date_filling', models.TextField()),
                ('last_name_change', models.TextField()),
                ('first_name_change', models.TextField()),
                ('middle_name_change', models.TextField()),
            ],
        ),
    ]
